---

- name: "Install the docker-ce packages"
  yum:
    name={{item}}
    state=latest
  with_items: "{{docker_packages}}"
  notify: restart docker

- name: Add the users to the {{docker_group}} local group
  user:
    groups='{{docker_group}}'
    user={{item}}
    append=True
  with_items: "{{docker_users}}"
  notify: restart docker

- name: Add the sudoers file for the docker group
  template: 
    src=sudo.j2
    dest=/etc/sudoers.d/docker
    mode=0600
    owner=root
    group=root
    validate="/usr/sbin/visudo -cf %s"

- import_tasks: run-test.yml
  when: docker_run_test | bool
